#!/bin/bash

# for reference. do not run this file

npm install -g express-generator
express --view=ejs
npm install
npm start

pip install --upgrade --user awsebcli
export PATH=~/.local/bin:$PATH
source ~/.bash_profile

eb init --platform node.js --region us-east-1
eb create --sample node-express-env

eb deploy
